services:
  admin-control-panel:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_MESSAGE=None
    container_name: admin-control-panel
    ports:
      - "8080:8080"
    restart: unless-stopped