server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Healthcheck
    location /healthz {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # Frontend (React o HTML)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia Flask (Python)
    location /api/ {
        proxy_pass http://api:5050/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/healthcheck {
        proxy_pass http://api:5050/api/healthcheck;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/inventario {
        proxy_pass http://api:5050/api/inventario;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/update {
        proxy_pass http://api:5050/api/update;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/descargar/csv {
        proxy_pass http://api:5050/api/descargar/csv;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|eot|ttf)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }
}